platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = ['$(FRAMEWORK_SEARCH_PATHS)']
          config.build_settings['ONLY_ACTIVE_ARCH'] = ['NO']
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = ['YES']
          config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ['arm64 i386']
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
          config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
  end
end
